### ISSUE TITLE
[Feature]-Dark Mode toggle

### ISSUE THREAD

**Issue by yash-gharat** [Sanjayng125/MERN-Travel-Tourism-App#1]
### Dark Mode Feature Implementation Guide
**Problem:**
Users accustomed to dark mode find it frustrating when unable to locate a theme toggle button on a website. 🌓

**Solution:**

1. State Management:

Utilize React Context API for efficient theme state management. This allows for easy access to the current theme throughout the application. ⚛️

2. Theme Styles:
Define CSS for light and dark themes, incorporating variables or separate files for modularity. This ensures that styling changes seamlessly when switching between themes. 🎨

3. Toggle Functionality:
Implement a toggle function to seamlessly switch between light and dark themes. This function dynamically updates the state and applies corresponding styles to the application. 🌗🌑

4. Additionally Theme Preference:
Optionally, store the user's theme preference in local storage for enhanced user experience across sessions. This ensures that the user's chosen theme persists between visits to the website. 💾

By implementing these steps, users can conveniently switch between light and dark modes, enhancing accessibility and user satisfaction. 🚀

**Comment by Sanjayng125** [comment]
Thank you for your suggestion as I'm still learning so I'll add it in my next project 😊👍

**Comment by Sanjayng125** [comment]
i built a simple movie app with NEXT JS i included dark theme in that project you can check it out and give it a star if you liked it ⭐👍
https://github.com/Sanjayng125/Movie-App-NextJS
